version: '3'
services:
  prisma-ro:
    image: prismagraphql/prisma-prod:1.28
    restart: always
    ports:
      - "8001:8001"
    environment:
      PRISMA_CONFIG: |
        port: 8001
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        rabbitUri: amqp://dqfeegng:APebV6-8G8u-xUwwKPm4TFgfMFTJeaBg@caterpillar.rmq.cloudamqp.com/dqfeegng
        managementApiEnabled: false
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  prisma-ro-1:
    image: prismagraphql/prisma-prod:1.28
    restart: always
    ports:
      - "8002:8002"
    environment:
      PRISMA_CONFIG: |
        port: 8002
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        rabbitUri: amqp://dqfeegng:APebV6-8G8u-xUwwKPm4TFgfMFTJeaBg@caterpillar.rmq.cloudamqp.com/dqfeegng
        managementApiEnabled: false
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
      - "8000:8000"
    environment:
      PRISMA_CONFIG: |
        port: 8000
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        rabbitUri: amqp://dqfeegng:APebV6-8G8u-xUwwKPm4TFgfMFTJeaBg@caterpillar.rmq.cloudamqp.com/dqfeegng
        managementApiEnabled: true
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    ports:
      - "13306:3306"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
      - ./legacy_db_sql/build/data/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
volumes:
  mysql:

networks:
  default:
